name: Update demo
on:
  push:
    branches:
      - main
jobs:
  test-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: checkout
        uses: actions/checkout@v4
      - name: setup repo
        run: npm install
      - name: codecheck
        run: npm run check
      - name: build
        run: BASE_URL='/${{ github.event.repository.name }}/' npm run build
      - name: update demo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch --all
          git checkout -f gh-pages
          git pull
          git checkout main .gitignore
          cp -r dist/* .
          git add .
          git commit -m "update demo $GITHUB_SHA"
          git push --set-upstream origin gh-pages
